GET http://localhost:3001/users

###

GET http://localhost:3001/users/5ec9884db5f38f20c5cf9cbc

###

POST http://localhost:3001/users
Content-Type: application/json

{
  "username": "testing1",
  "password": "password",
  "role": "user"
}

###
POST http://localhost:3001/users/login
Content-Type: application/json

{
  "username": "testing1",
  "password": "password"
}